### ISSUE TITLE
update `ranges` with ? `updateDaterangepicker` 

### ISSUE THREAD

**Issue by ltuijnder** [trafficonese/daterangepicker#7]
Hi @trafficonese. First of all thank you for making this package available. 
 
I have noticed that not all arguments that one gives to `daterangepicker` are also updateable with `updateDaterangepicker`. Most notable the `ranges`. 

Would it be possible to also have these included?

eg.:
```R
      updateDaterangepicker(session, "daterange",
#       ranges = list("Today" = Sys.Date()), # -> Not possible. 
        options = list( linkedCalendars = FALSE)
      )
``` 

Other arguments like: `language`, `style` and `class` could also maybe be included to be updated.

**Comment by mzorko** [comment]
Hi. Anything on this? Would be super useful to update ranges.

**Comment by trafficonese** [comment]
Thanks for the suggestions, I will look into it. That definitly sounds like a great addition.

**Comment by trafficonese** [comment]
It seems like `style` and `class` are doable, but the `language` cannot be changed, since it is set globally in the initializing-step. Would that be really useful? I think once a correct locale is set, it should stay that way or?

Unfortunately, the library doesn't offer an official way to update the ranges. I think I have a working fix, but I'm not sure what side-effects that might have, since I just change the range-list in the HTML and replace it with the new one. 

One problem for example seems to be, that the new range doesn't respect the minimum date.

**Comment by ltuijnder** [comment]
@trafficonese 

This post: https://stackoverflow.com/questions/18955397/update-the-selected-dates-of-date-range-picker-for-twitter-bootstrap does show that you can update it via javascript. Not sure if you have to perform some manual checks for the min and max

**Comment by ltuijnder** [comment]
And I also agree that language might not be the most interesting to update. So I do not think that this is a huge issue. But would have been nice for completion's sake.

**Comment by trafficonese** [comment]
Yes, I was wrong. I figured it out already.
The SO-answer doesn't really update the predefined ranges, but the start and endDate.

Anyway, I'll push a fix in a bit. :)

**Comment by trafficonese** [comment]
[6382bd6](https://github.com/trafficonese/daterangepicker/commit/6382bd6a7511b3555912124dd0b9d77ef2edc6de) allows now to update ranges. Feel free to reopen if you find any issue.
